---
title: "week_2_solution_kim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# 3.1
```{r}
p <- c(0.50,0.60,0.40,0.30)
n <- c(200,200,200,200)

sum(n*p)/sum(n)
```


# 3.3
```{r}
norms <- data.frame(norm1=rnorm(100,10,1),norm2=rnorm(100,1,10),norm3=rnorm(100,1,3)) %>% 
  pivot_longer(c(norm1,norm2,norm3))

ggplot(norms)+aes(x=value,col=name)+geom_density()+theme_bw()

```


# 3.4
```{r}
pois <- rpois(100,0.4)
ggplot()+aes(x=pois)+geom_bar()

```



# 3.5
```{r}
pois2 <- rpois(20,0.3)
ggplot()+aes(x=pois2)+geom_bar()
```


# 3.6
a)
```{r}
mean_norm <- 35
sd_norm <- 10

x <- rnorm(100,mean_norm,sd_norm)

a <- 15/sd_norm
b <- 100-mean_norm*a

sd(b+a*x)
mean(b+a*x)

b
a
```

b)
```{r}
0*a+b
50*a+b

```


# 4.1
```{r}
n <- 500
p_noinc <- 0.4 
p_inc <- 0.5

0.5-0.4
sqrt(p_noinc*(1-p_noinc)/n + p_inc*(1-p_inc)/n)
```


# 4.2
Worst case scenario is 50/50 voting
```{r}
p_worst <- 0.5
n <- (p_worst*(1-p_worst) + p_worst*(1-p_worst))/0.05^2
0.05 == sqrt(0.5*(1-0.5)/n + 0.5*(1-0.5)/n)
n*2
```


# 4.3
```{r}
n <- 20
p_good <- 0.4
p_bad <- 0.3

se = sqrt(p_good*(1-p_good)/n + p_bad*(1-p_bad)/n)

0.4-0.3 + se*qt(0.2565,n-1)
```
Around 25%

# 4.4
```{r}
p_good <- 0.4
p_bad <- 0.3

n = (p_good*(1-p_good) + p_bad*(1-p_bad))/(0.1/1.96)^2

n
```


# 4.5
```{r}
cov <- read_csv('../owid-covid-data.csv') 

cov <- cov %>% 
  mutate(date = as.character(date))  %>% 
  filter(date == "2020-11-20")


sample_cov <- sample(cov$total_cases,20)
sample_cov
```



# 3.10
```{r}

```


# 4.11


# 3.2
```{r}
p <- c(0.50,0.60,0.40,0.30)
n <- c(200,250,300,250)

new_prop <- 0.4
p_new = new_prop*sum(n)/length(n)/n

sum(n*p_new)/sum(n)

```


# 3.8
```{r}
corr = 0.3

husband_mean = 69.1
husband_sd = 2.7

wife_mean = 63.7
wife_sd = 2.9

avg_mean = husband_mean/2 + wife_mean/2 
avg_sd = sqrt(0.5^2*husband_sd^2+0.5^2*wife_sd^2+corr*0.5^2*wife_sd*husband_sd)

avg_mean
avg_sd
```


# 4.7
```{r}
n = 50
s = 0

p = (s+2)/(50+4)
0 + sqrt(p*(1-p)/(n+4))*qt(c(0.025,0.975),n-1)

```
